// Bilingual UI strings: English + Telugu.
// Usage: t('key') returns the string in the currently selected language.
window.STRINGS = {
  en: {
    appName: "Srikakulam Python Class",
    tagline: "Learn Python & AI basics — right from your home!",
    iAmStudent: "I am a Student",
    iAmTeacher: "I am the Teacher",
    chooseLanguage: "Choose language",
    joinClass: "Join your class",
    yourName: "Your name",
    classCode: "Class code (ask your teacher)",
    yourPin: "Secret PIN (at least 4 characters)",
    pinHelp: "Choose any PIN the first time. Use the same one every time you join, even on a different phone.",
    wrongPin: "That PIN doesn't match this name — ask your teacher if you forgot it.",
    join: "Join",
    lessons: "Lessons",
    assignments: "Homework",
    codeEditor: "Code Editor",
    run: "Run",
    running: "Running...",
    output: "Output",
    submit: "Submit homework",
    submitted: "Submitted! Your teacher will check it soon.",
    resetCode: "Reset to starter code",
    loadingPython: "Loading Python (first time only, please wait)...",
    pythonReady: "Python is ready!",
    selectAssignment: "Select a homework assignment",
    noAssignments: "No homework has been posted yet. Check back soon!",
    yourSubmissions: "Your past submissions",
    score: "Score",
    feedback: "Teacher's feedback",
    notGradedYet: "Not checked yet",
    teacherLogin: "Teacher Login",
    email: "Email",
    password: "Password",
    login: "Log in",
    signUp: "First time? Create teacher account",
    setupCode: "Teacher setup code",
    dashboard: "Dashboard",
    createAssignment: "Create new homework",
    title: "Title",
    titleTe: "Title (Telugu, optional)",
    instructions: "Instructions",
    instructionsTe: "Instructions (Telugu, optional)",
    translating: "Translating...",
    translateBtn: "Translate to Telugu",
    autoTranslateNote: "Fills in automatically from the English above — feel free to edit it. If it doesn't, tap \"Translate to Telugu\".",
    hintsLabel: "Hints (optional, one per line)",
    hintsLabelTe: "Hints (Telugu, optional, one per line)",
    hintsHelp: "Each line becomes one hint. Students reveal them one at a time, starting with the first line.",
    showHint: "Show a hint",
    showNextHint: "Show next hint",
    hint: "Hint",
    dueDate: "Due date (optional)",
    due: "Due",
    starterCode: "Starter code students will see",
    post: "Post homework",
    posted: "Homework posted!",
    yourHomework: "Your homework",
    noHomeworkYet: "You haven't posted any homework yet.",
    edit: "Edit",
    delete: "Delete",
    cancelEdit: "Cancel",
    saveChanges: "Save changes",
    editingLabel: "Editing:",
    confirmDeleteHomework: "Delete this homework? Existing student submissions for it will stay, but students won't see it anymore.",
    submissionsFor: "Submissions",
    student: "Student",
    when: "Submitted",
    viewCode: "View code",
    giveScore: "Score (0-10)",
    giveFeedback: "Write feedback",
    saveGrade: "Save grade",
    graded: "Saved!",
    logout: "Log out",
    back: "Back",
    manageClass: "Class codes",
    addClass: "Add a new class code",
    className: "Class name (e.g. Batch 1 - Oct 2026)",
    newClassCode: "New class code",
    createClass: "Create class",
    noSubmissions: "No submissions yet for this homework.",
    installApp: "Install this app on your phone",
    installHint: "Tap your browser menu and choose \"Add to Home Screen\" so this opens like an app, even without opening a browser.",
    codeError: "There's an error in the code — check the output below.",
    welcomeBack: "Welcome back",
    changeLanguage: "తెలుగు",
    home: "Home",
    switchStudent: "Not you? Switch student"
  },
  te: {
    appName: "శ్రీకాకుళం పైథాన్ తరగతి",
    tagline: "పైథాన్ మరియు AI ప్రాథమికాలు మీ ఇంటి నుండే నేర్చుకోండి!",
    iAmStudent: "నేను విద్యార్థిని",
    iAmTeacher: "నేను ఉపాధ్యాయుడిని",
    chooseLanguage: "భాష ఎంచుకోండి",
    joinClass: "మీ తరగతిలో చేరండి",
    yourName: "మీ పేరు",
    classCode: "తరగతి కోడ్ (మీ ఉపాధ్యాయుడిని అడగండి)",
    yourPin: "రహస్య పిన్ (కనీసం 4 అక్షరాలు)",
    pinHelp: "మొదటిసారి ఏదైనా పిన్ ఎంచుకోండి. వేరే ఫోన్‌లో అయినా ప్రతిసారీ అదే పిన్ వాడండి.",
    wrongPin: "ఈ పేరుకు ఈ పిన్ సరిపోలలేదు — మర్చిపోతే మీ ఉపాధ్యాయుడిని అడగండి.",
    join: "చేరండి",
    lessons: "పాఠాలు",
    assignments: "హోంవర్క్",
    codeEditor: "కోడ్ ఎడిటర్",
    run: "రన్ చేయండి",
    running: "నడుస్తోంది...",
    output: "అవుట్‌పుట్",
    submit: "హోంవర్క్ సమర్పించండి",
    submitted: "సమర్పించారు! మీ ఉపాధ్యాయుడు త్వరలో తనిఖీ చేస్తారు.",
    resetCode: "మొదటి కోడ్‌కు మార్చండి",
    loadingPython: "పైథాన్ లోడ్ అవుతోంది (మొదటిసారి మాత్రమే, దయచేసి వేచి ఉండండి)...",
    pythonReady: "పైథాన్ సిద్ధంగా ఉంది!",
    selectAssignment: "ఒక హోంవర్క్ ఎంచుకోండి",
    noAssignments: "ఇంకా హోంవర్క్ పోస్ట్ చేయలేదు. త్వరలో చూడండి!",
    yourSubmissions: "మీ గత సమర్పణలు",
    score: "స్కోర్",
    feedback: "ఉపాధ్యాయుని అభిప్రాయం",
    notGradedYet: "ఇంకా తనిఖీ చేయలేదు",
    teacherLogin: "ఉపాధ్యాయుని లాగిన్",
    email: "ఇమెయిల్",
    password: "పాస్‌వర్డ్",
    login: "లాగిన్ చేయండి",
    signUp: "మొదటిసారా? ఉపాధ్యాయ ఖాతా సృష్టించండి",
    setupCode: "ఉపాధ్యాయ సెటప్ కోడ్",
    dashboard: "డాష్‌బోర్డ్",
    createAssignment: "కొత్త హోంవర్క్ సృష్టించండి",
    title: "శీర్షిక",
    titleTe: "శీర్షిక (తెలుగు, ఐచ్ఛికం)",
    instructions: "సూచనలు",
    instructionsTe: "సూచనలు (తెలుగు, ఐచ్ఛికం)",
    translating: "అనువదిస్తోంది...",
    translateBtn: "తెలుగులోకి అనువదించండి",
    autoTranslateNote: "పైన ఇంగ్లీష్ నుండి స్వయంచాలకంగా నింపబడుతుంది — మీరు కావాలంటే మార్చవచ్చు. కాకపోతే \"తెలుగులోకి అనువదించండి\" నొక్కండి.",
    hintsLabel: "హింట్స్ (ఐచ్ఛికం, ఒక్కో లైన్‌లో ఒకటి)",
    hintsLabelTe: "హింట్స్ (తెలుగు, ఐచ్ఛికం, ఒక్కో లైన్‌లో ఒకటి)",
    hintsHelp: "ప్రతి లైన్ ఒక హింట్ అవుతుంది. విద్యార్థులు మొదటి లైన్ నుండి ఒక్కొక్కటిగా చూస్తారు.",
    showHint: "హింట్ చూపించు",
    showNextHint: "తదుపరి హింట్ చూపించు",
    hint: "హింట్",
    dueDate: "గడువు తేదీ (ఐచ్ఛికం)",
    due: "గడువు",
    starterCode: "విద్యార్థులు చూసే ప్రారంభ కోడ్",
    post: "హోంవర్క్ పోస్ట్ చేయండి",
    posted: "హోంవర్క్ పోస్ట్ చేయబడింది!",
    yourHomework: "మీ హోంవర్క్",
    noHomeworkYet: "మీరు ఇంకా ఏ హోంవర్క్ పోస్ట్ చేయలేదు.",
    edit: "సవరించండి",
    delete: "తొలగించండి",
    cancelEdit: "రద్దు చేయండి",
    saveChanges: "మార్పులను సేవ్ చేయండి",
    editingLabel: "సవరిస్తున్నారు:",
    confirmDeleteHomework: "ఈ హోంవర్క్‌ను తొలగించాలా? ఇప్పటికే ఉన్న విద్యార్థుల సమర్పణలు అలాగే ఉంటాయి, కానీ విద్యార్థులకు ఇకపై కనిపించదు.",
    submissionsFor: "సమర్పణలు",
    student: "విద్యార్థి",
    when: "సమర్పించిన సమయం",
    viewCode: "కోడ్ చూడండి",
    giveScore: "స్కోర్ (0-10)",
    giveFeedback: "అభిప్రాయం రాయండి",
    saveGrade: "గ్రేడ్ సేవ్ చేయండి",
    graded: "సేవ్ చేయబడింది!",
    logout: "లాగ్ అవుట్",
    back: "వెనుకకు",
    manageClass: "తరగతి కోడ్‌లు",
    addClass: "కొత్త తరగతి కోడ్ జోడించండి",
    className: "తరగతి పేరు (ఉదా. బ్యాచ్ 1 - అక్టోబర్ 2026)",
    newClassCode: "కొత్త తరగతి కోడ్",
    createClass: "తరగతి సృష్టించండి",
    noSubmissions: "ఈ హోంవర్క్‌కు ఇంకా సమర్పణలు లేవు.",
    installApp: "మీ ఫోన్‌లో ఈ యాప్‌ను ఇన్‌స్టాల్ చేయండి",
    installHint: "మీ బ్రౌజర్ మెనూను నొక్కి \"Add to Home Screen\" ఎంచుకోండి, తద్వారా ఇది బ్రౌజర్ తెరవకుండానే యాప్‌లా తెరుచుకుంటుంది.",
    codeError: "కోడ్‌లో పొరపాటు ఉంది — దిగువ అవుట్‌పుట్ చూడండి.",
    welcomeBack: "తిరిగి స్వాగతం",
    changeLanguage: "English",
    home: "హోమ్",
    switchStudent: "మీరు కాదా? విద్యార్థిని మార్చండి"
  }
};

window.getLang = function () {
  try { return localStorage.getItem("pyclass_lang") || "en"; } catch (e) { return "en"; }
};
window.setLang = function (lang) {
  try { localStorage.setItem("pyclass_lang", lang); } catch (e) {}
};
window.t = function (key) {
  const lang = window.getLang();
  return (window.STRINGS[lang] && window.STRINGS[lang][key]) || window.STRINGS.en[key] || key;
};
window.applyStrings = function () {
  document.querySelectorAll("[data-t]").forEach(function (el) {
    el.textContent = window.t(el.getAttribute("data-t"));
  });
  document.querySelectorAll("[data-t-placeholder]").forEach(function (el) {
    el.setAttribute("placeholder", window.t(el.getAttribute("data-t-placeholder")));
  });
  document.documentElement.lang = window.getLang();
};
